global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus-1"
    static_configs:
      - targets: ["localhost:9090"]

remote_write:
  - url: "http://localhost:9093/api/v1/write"  # Forward to the second Prometheus instance

