global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "remote-prometheus"
    static_configs:
      - targets: ["localhost:9093"]  # Self-monitoring

# Enable WAL replay for Remote Write
storage:
  tsdb:
    out_of_order_time_window: 30m

